name: Bug Report
description: Something isn't working correctly
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Minimal .push code or steps to reproduce the issue.
      render: text
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Output
      description: Paste the full error message if applicable.
      render: text
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Pushkin Version
      placeholder: "0.0.1-alpha.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: input
    id: bun-version
    attributes:
      label: Bun Version
      placeholder: "1.3.4"
    validations:
      required: false