name: Documentation
description: Report missing, incorrect, or unclear documentation
labels: ["docs"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is missing, wrong, or unclear?
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where in the docs is the issue? (URL, file path, or section name)
      placeholder: "README.md, Language Guide section"
    validations:
      required: false

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve it?
    validations:
      required: false