name: Feature Request
description: Suggest a new language feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature would you like to see?
    validations:
      required: true

  - type: textarea
    id: syntax
    attributes:
      label: Proposed Syntax
      description: If this involves new syntax, show what it would look like in .push code.
      render: text
    validations:
      required: false

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this useful? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about.
    validations:
      required: false